export type FontawesomeIcon =
  "fa-500px"
  | "fa-address-book"
  | "fa-address-book-o"
  | "fa-address-card"
  | "fa-address-card-o"
  | "fa-adjust"
  | "fa-adn"
  | "fa-align-center"
  | "fa-align-justify"
  | "fa-align-left"
  | "fa-align-right"
  | "fa-amazon"
  | "fa-ambulance"
  | "fa-american-sign-language-interpreting"
  | "fa-anchor"
  | "fa-android"
  | "fa-angellist"
  | "fa-angle-double-down"
  | "fa-angle-double-left"
  | "fa-angle-double-right"
  | "fa-angle-double-up"
  | "fa-angle-down"
  | "fa-angle-left"
  | "fa-angle-right"
  | "fa-angle-up"
  | "fa-apple"
  | "fa-archive"
  | "fa-area-chart"
  | "fa-arrow-circle-down"
  | "fa-arrow-circle-left"
  | "fa-arrow-circle-o-down"
  | "fa-arrow-circle-o-left"
  | "fa-arrow-circle-o-right"
  | "fa-arrow-circle-o-up"
  | "fa-arrow-circle-right"
  | "fa-arrow-circle-up"
  | "fa-arrow-down"
  | "fa-arrow-left"
  | "fa-arrow-right"
  | "fa-arrow-up"
  | "fa-arrows"
  | "fa-arrows-alt"
  | "fa-arrows-h"
  | "fa-arrows-v"
  | "fa-asl-interpreting"
  | "fa-assistive-listening-systems"
  | "fa-asterisk"
  | "fa-at"
  | "fa-audio-description"
  | "fa-automobile"
  | "fa-backward"
  | "fa-balance-scale"
  | "fa-ban"
  | "fa-bandcamp"
  | "fa-bank"
  | "fa-bar-chart"
  | "fa-bar-chart-o"
  | "fa-barcode"
  | "fa-bars"
  | "fa-bath"
  | "fa-bathtub"
  | "fa-battery"
  | "fa-battery-0"
  | "fa-battery-1"
  | "fa-battery-2"
  | "fa-battery-3"
  | "fa-battery-4"
  | "fa-battery-empty"
  | "fa-battery-full"
  | "fa-battery-half"
  | "fa-battery-quarter"
  | "fa-battery-three-quarters"
  | "fa-bed"
  | "fa-beer"
  | "fa-behance"
  | "fa-behance-square"
  | "fa-bell"
  | "fa-bell-o"
  | "fa-bell-slash"
  | "fa-bell-slash-o"
  | "fa-bicycle"
  | "fa-binoculars"
  | "fa-birthday-cake"
  | "fa-bitbucket"
  | "fa-bitbucket-square"
  | "fa-bitcoin"
  | "fa-black-tie"
  | "fa-blind"
  | "fa-bluetooth"
  | "fa-bluetooth-b"
  | "fa-bold"
  | "fa-bolt"
  | "fa-bomb"
  | "fa-book"
  | "fa-bookmark"
  | "fa-bookmark-o"
  | "fa-braille"
  | "fa-briefcase"
  | "fa-btc"
  | "fa-bug"
  | "fa-building"
  | "fa-building-o"
  | "fa-bullhorn"
  | "fa-bullseye"
  | "fa-bus"
  | "fa-buysellads"
  | "fa-cab"
  | "fa-calculator"
  | "fa-calendar"
  | "fa-calendar-check-o"
  | "fa-calendar-minus-o"
  | "fa-calendar-o"
  | "fa-calendar-plus-o"
  | "fa-calendar-times-o"
  | "fa-camera"
  | "fa-camera-retro"
  | "fa-car"
  | "fa-caret-down"
  | "fa-caret-left"
  | "fa-caret-right"
  | "fa-caret-square-o-down"
  | "fa-caret-square-o-left"
  | "fa-caret-square-o-right"
  | "fa-caret-square-o-up"
  | "fa-caret-up"
  | "fa-cart-arrow-down"
  | "fa-cart-plus"
  | "fa-cc"
  | "fa-cc-amex"
  | "fa-cc-diners-club"
  | "fa-cc-discover"
  | "fa-cc-jcb"
  | "fa-cc-mastercard"
  | "fa-cc-paypal"
  | "fa-cc-stripe"
  | "fa-cc-visa"
  | "fa-certificate"
  | "fa-chain"
  | "fa-chain-broken"
  | "fa-check"
  | "fa-check-circle"
  | "fa-check-circle-o"
  | "fa-check-square"
  | "fa-check-square-o"
  | "fa-chevron-circle-down"
  | "fa-chevron-circle-left"
  | "fa-chevron-circle-right"
  | "fa-chevron-circle-up"
  | "fa-chevron-down"
  | "fa-chevron-left"
  | "fa-chevron-right"
  | "fa-chevron-up"
  | "fa-child"
  | "fa-chrome"
  | "fa-circle"
  | "fa-circle-o"
  | "fa-circle-o-notch"
  | "fa-circle-thin"
  | "fa-clipboard"
  | "fa-clock-o"
  | "fa-clone"
  | "fa-close"
  | "fa-cloud"
  | "fa-cloud-download"
  | "fa-cloud-upload"
  | "fa-cny"
  | "fa-code"
  | "fa-code-fork"
  | "fa-codepen"
  | "fa-codiepie"
  | "fa-coffee"
  | "fa-cog"
  | "fa-cogs"
  | "fa-columns"
  | "fa-comment"
  | "fa-comment-o"
  | "fa-commenting"
  | "fa-commenting-o"
  | "fa-comments"
  | "fa-comments-o"
  | "fa-compass"
  | "fa-compress"
  | "fa-connectdevelop"
  | "fa-contao"
  | "fa-copy"
  | "fa-copyright"
  | "fa-creative-commons"
  | "fa-credit-card"
  | "fa-credit-card-alt"
  | "fa-crop"
  | "fa-crosshairs"
  | "fa-css3"
  | "fa-cube"
  | "fa-cubes"
  | "fa-cut"
  | "fa-cutlery"
  | "fa-dashboard"
  | "fa-dashcube"
  | "fa-database"
  | "fa-deaf"
  | "fa-deafness"
  | "fa-dedent"
  | "fa-delicious"
  | "fa-desktop"
  | "fa-deviantart"
  | "fa-diamond"
  | "fa-digg"
  | "fa-dollar"
  | "fa-dot-circle-o"
  | "fa-download"
  | "fa-dribbble"
  | "fa-drivers-license"
  | "fa-drivers-license-o"
  | "fa-dropbox"
  | "fa-drupal"
  | "fa-edge"
  | "fa-edit"
  | "fa-eercast"
  | "fa-eject"
  | "fa-ellipsis-h"
  | "fa-ellipsis-v"
  | "fa-empire"
  | "fa-envelope"
  | "fa-envelope-o"
  | "fa-envelope-open"
  | "fa-envelope-open-o"
  | "fa-envelope-square"
  | "fa-envira"
  | "fa-eraser"
  | "fa-etsy"
  | "fa-eur"
  | "fa-euro"
  | "fa-exchange"
  | "fa-exclamation"
  | "fa-exclamation-circle"
  | "fa-exclamation-triangle"
  | "fa-expand"
  | "fa-expeditedssl"
  | "fa-external-link"
  | "fa-external-link-square"
  | "fa-eye"
  | "fa-eye-slash"
  | "fa-eyedropper"
  | "fa-fa"
  | "fa-facebook"
  | "fa-facebook-f"
  | "fa-facebook-official"
  | "fa-facebook-square"
  | "fa-fast-backward"
  | "fa-fast-forward"
  | "fa-fax"
  | "fa-feed"
  | "fa-female"
  | "fa-fighter-jet"
  | "fa-file"
  | "fa-file-archive-o"
  | "fa-file-audio-o"
  | "fa-file-code-o"
  | "fa-file-excel-o"
  | "fa-file-image-o"
  | "fa-file-movie-o"
  | "fa-file-o"
  | "fa-file-pdf-o"
  | "fa-file-photo-o"
  | "fa-file-picture-o"
  | "fa-file-powerpoint-o"
  | "fa-file-sound-o"
  | "fa-file-text"
  | "fa-file-text-o"
  | "fa-file-video-o"
  | "fa-file-word-o"
  | "fa-file-zip-o"
  | "fa-files-o"
  | "fa-film"
  | "fa-filter"
  | "fa-fire"
  | "fa-fire-extinguisher"
  | "fa-firefox"
  | "fa-first-order"
  | "fa-flag"
  | "fa-flag-checkered"
  | "fa-flag-o"
  | "fa-flash"
  | "fa-flask"
  | "fa-flickr"
  | "fa-floppy-o"
  | "fa-folder"
  | "fa-folder-o"
  | "fa-folder-open"
  | "fa-folder-open-o"
  | "fa-font"
  | "fa-font-awesome"
  | "fa-fonticons"
  | "fa-fort-awesome"
  | "fa-forumbee"
  | "fa-forward"
  | "fa-foursquare"
  | "fa-free-code-camp"
  | "fa-frown-o"
  | "fa-futbol-o"
  | "fa-gamepad"
  | "fa-gavel"
  | "fa-gbp"
  | "fa-ge"
  | "fa-gear"
  | "fa-gears"
  | "fa-genderless"
  | "fa-get-pocket"
  | "fa-gg"
  | "fa-gg-circle"
  | "fa-gift"
  | "fa-git"
  | "fa-git-square"
  | "fa-github"
  | "fa-github-alt"
  | "fa-github-square"
  | "fa-gitlab"
  | "fa-gittip"
  | "fa-glass"
  | "fa-glide"
  | "fa-glide-g"
  | "fa-globe"
  | "fa-google"
  | "fa-google-plus"
  | "fa-google-plus-circle"
  | "fa-google-plus-official"
  | "fa-google-plus-square"
  | "fa-google-wallet"
  | "fa-graduation-cap"
  | "fa-gratipay"
  | "fa-grav"
  | "fa-group"
  | "fa-h-square"
  | "fa-hacker-news"
  | "fa-hand-grab-o"
  | "fa-hand-lizard-o"
  | "fa-hand-o-down"
  | "fa-hand-o-left"
  | "fa-hand-o-right"
  | "fa-hand-o-up"
  | "fa-hand-paper-o"
  | "fa-hand-peace-o"
  | "fa-hand-pointer-o"
  | "fa-hand-rock-o"
  | "fa-hand-scissors-o"
  | "fa-hand-spock-o"
  | "fa-hand-stop-o"
  | "fa-handshake-o"
  | "fa-hard-of-hearing"
  | "fa-hashtag"
  | "fa-hdd-o"
  | "fa-header"
  | "fa-headphones"
  | "fa-heart"
  | "fa-heart-o"
  | "fa-heartbeat"
  | "fa-history"
  | "fa-home"
  | "fa-hospital-o"
  | "fa-hotel"
  | "fa-hourglass"
  | "fa-hourglass-1"
  | "fa-hourglass-2"
  | "fa-hourglass-3"
  | "fa-hourglass-end"
  | "fa-hourglass-half"
  | "fa-hourglass-o"
  | "fa-hourglass-start"
  | "fa-houzz"
  | "fa-html5"
  | "fa-i-cursor"
  | "fa-id-badge"
  | "fa-id-card"
  | "fa-id-card-o"
  | "fa-ils"
  | "fa-image"
  | "fa-imdb"
  | "fa-inbox"
  | "fa-indent"
  | "fa-industry"
  | "fa-info"
  | "fa-info-circle"
  | "fa-inr"
  | "fa-instagram"
  | "fa-institution"
  | "fa-internet-explorer"
  | "fa-intersex"
  | "fa-ioxhost"
  | "fa-italic"
  | "fa-joomla"
  | "fa-jpy"
  | "fa-jsfiddle"
  | "fa-key"
  | "fa-keyboard-o"
  | "fa-krw"
  | "fa-language"
  | "fa-laptop"
  | "fa-lastfm"
  | "fa-lastfm-square"
  | "fa-leaf"
  | "fa-leanpub"
  | "fa-legal"
  | "fa-lemon-o"
  | "fa-level-down"
  | "fa-level-up"
  | "fa-life-bouy"
  | "fa-life-buoy"
  | "fa-life-ring"
  | "fa-life-saver"
  | "fa-lightbulb-o"
  | "fa-line-chart"
  | "fa-link"
  | "fa-linkedin"
  | "fa-linkedin-square"
  | "fa-linode"
  | "fa-linux"
  | "fa-list"
  | "fa-list-alt"
  | "fa-list-ol"
  | "fa-list-ul"
  | "fa-location-arrow"
  | "fa-lock"
  | "fa-long-arrow-down"
  | "fa-long-arrow-left"
  | "fa-long-arrow-right"
  | "fa-long-arrow-up"
  | "fa-low-vision"
  | "fa-magic"
  | "fa-magnet"
  | "fa-mail-forward"
  | "fa-mail-reply"
  | "fa-mail-reply-all"
  | "fa-male"
  | "fa-map"
  | "fa-map-marker"
  | "fa-map-o"
  | "fa-map-pin"
  | "fa-map-signs"
  | "fa-mars"
  | "fa-mars-double"
  | "fa-mars-stroke"
  | "fa-mars-stroke-h"
  | "fa-mars-stroke-v"
  | "fa-maxcdn"
  | "fa-meanpath"
  | "fa-medium"
  | "fa-medkit"
  | "fa-meetup"
  | "fa-meh-o"
  | "fa-mercury"
  | "fa-microchip"
  | "fa-microphone"
  | "fa-microphone-slash"
  | "fa-minus"
  | "fa-minus-circle"
  | "fa-minus-square"
  | "fa-minus-square-o"
  | "fa-mixcloud"
  | "fa-mobile"
  | "fa-mobile-phone"
  | "fa-modx"
  | "fa-money"
  | "fa-moon-o"
  | "fa-mortar-board"
  | "fa-motorcycle"
  | "fa-mouse-pointer"
  | "fa-music"
  | "fa-navicon"
  | "fa-neuter"
  | "fa-newspaper-o"
  | "fa-object-group"
  | "fa-object-ungroup"
  | "fa-odnoklassniki"
  | "fa-odnoklassniki-square"
  | "fa-opencart"
  | "fa-openid"
  | "fa-opera"
  | "fa-optin-monster"
  | "fa-outdent"
  | "fa-pagelines"
  | "fa-paint-brush"
  | "fa-paper-plane"
  | "fa-paper-plane-o"
  | "fa-paperclip"
  | "fa-paragraph"
  | "fa-paste"
  | "fa-pause"
  | "fa-pause-circle"
  | "fa-pause-circle-o"
  | "fa-paw"
  | "fa-paypal"
  | "fa-pencil"
  | "fa-pencil-square"
  | "fa-pencil-square-o"
  | "fa-percent"
  | "fa-phone"
  | "fa-phone-square"
  | "fa-photo"
  | "fa-picture-o"
  | "fa-pie-chart"
  | "fa-pied-piper"
  | "fa-pied-piper-alt"
  | "fa-pied-piper-pp"
  | "fa-pinterest"
  | "fa-pinterest-p"
  | "fa-pinterest-square"
  | "fa-plane"
  | "fa-play"
  | "fa-play-circle"
  | "fa-play-circle-o"
  | "fa-plug"
  | "fa-plus"
  | "fa-plus-circle"
  | "fa-plus-square"
  | "fa-plus-square-o"
  | "fa-podcast"
  | "fa-power-off"
  | "fa-print"
  | "fa-product-hunt"
  | "fa-puzzle-piece"
  | "fa-qq"
  | "fa-qrcode"
  | "fa-question"
  | "fa-question-circle"
  | "fa-question-circle-o"
  | "fa-quora"
  | "fa-quote-left"
  | "fa-quote-right"
  | "fa-ra"
  | "fa-random"
  | "fa-ravelry"
  | "fa-rebel"
  | "fa-recycle"
  | "fa-reddit"
  | "fa-reddit-alien"
  | "fa-reddit-square"
  | "fa-refresh"
  | "fa-registered"
  | "fa-remove"
  | "fa-renren"
  | "fa-reorder"
  | "fa-repeat"
  | "fa-reply"
  | "fa-reply-all"
  | "fa-resistance"
  | "fa-retweet"
  | "fa-rmb"
  | "fa-road"
  | "fa-rocket"
  | "fa-rotate-left"
  | "fa-rotate-right"
  | "fa-rouble"
  | "fa-rss"
  | "fa-rss-square"
  | "fa-rub"
  | "fa-ruble"
  | "fa-rupee"
  | "fa-s15"
  | "fa-safari"
  | "fa-save"
  | "fa-scissors"
  | "fa-scribd"
  | "fa-search"
  | "fa-search-minus"
  | "fa-search-plus"
  | "fa-sellsy"
  | "fa-send"
  | "fa-send-o"
  | "fa-server"
  | "fa-share"
  | "fa-share-alt"
  | "fa-share-alt-square"
  | "fa-share-square"
  | "fa-share-square-o"
  | "fa-shekel"
  | "fa-sheqel"
  | "fa-shield"
  | "fa-ship"
  | "fa-shirtsinbulk"
  | "fa-shopping-bag"
  | "fa-shopping-basket"
  | "fa-shopping-cart"
  | "fa-shower"
  | "fa-sign-in"
  | "fa-sign-language"
  | "fa-sign-out"
  | "fa-signal"
  | "fa-signing"
  | "fa-simplybuilt"
  | "fa-sitemap"
  | "fa-skyatlas"
  | "fa-skype"
  | "fa-slack"
  | "fa-sliders"
  | "fa-slideshare"
  | "fa-smile-o"
  | "fa-snapchat"
  | "fa-snapchat-ghost"
  | "fa-snapchat-square"
  | "fa-snowflake-o"
  | "fa-soccer-ball-o"
  | "fa-sort"
  | "fa-sort-alpha-asc"
  | "fa-sort-alpha-desc"
  | "fa-sort-amount-asc"
  | "fa-sort-amount-desc"
  | "fa-sort-asc"
  | "fa-sort-desc"
  | "fa-sort-down"
  | "fa-sort-numeric-asc"
  | "fa-sort-numeric-desc"
  | "fa-sort-up"
  | "fa-soundcloud"
  | "fa-space-shuttle"
  | "fa-spinner"
  | "fa-spoon"
  | "fa-spotify"
  | "fa-square"
  | "fa-square-o"
  | "fa-stack-exchange"
  | "fa-stack-overflow"
  | "fa-star"
  | "fa-star-half"
  | "fa-star-half-empty"
  | "fa-star-half-full"
  | "fa-star-half-o"
  | "fa-star-o"
  | "fa-steam"
  | "fa-steam-square"
  | "fa-step-backward"
  | "fa-step-forward"
  | "fa-stethoscope"
  | "fa-sticky-note"
  | "fa-sticky-note-o"
  | "fa-stop"
  | "fa-stop-circle"
  | "fa-stop-circle-o"
  | "fa-street-view"
  | "fa-strikethrough"
  | "fa-stumbleupon"
  | "fa-stumbleupon-circle"
  | "fa-subscript"
  | "fa-subway"
  | "fa-suitcase"
  | "fa-sun-o"
  | "fa-superpowers"
  | "fa-superscript"
  | "fa-support"
  | "fa-table"
  | "fa-tablet"
  | "fa-tachometer"
  | "fa-tag"
  | "fa-tags"
  | "fa-tasks"
  | "fa-taxi"
  | "fa-telegram"
  | "fa-television"
  | "fa-tencent-weibo"
  | "fa-terminal"
  | "fa-text-height"
  | "fa-text-width"
  | "fa-th"
  | "fa-th-large"
  | "fa-th-list"
  | "fa-themeisle"
  | "fa-thermometer"
  | "fa-thermometer-0"
  | "fa-thermometer-1"
  | "fa-thermometer-2"
  | "fa-thermometer-3"
  | "fa-thermometer-4"
  | "fa-thermometer-empty"
  | "fa-thermometer-full"
  | "fa-thermometer-half"
  | "fa-thermometer-quarter"
  | "fa-thermometer-three-quarters"
  | "fa-thumb-tack"
  | "fa-thumbs-down"
  | "fa-thumbs-o-down"
  | "fa-thumbs-o-up"
  | "fa-thumbs-up"
  | "fa-ticket"
  | "fa-times"
  | "fa-times-circle"
  | "fa-times-circle-o"
  | "fa-times-rectangle"
  | "fa-times-rectangle-o"
  | "fa-tint"
  | "fa-toggle-down"
  | "fa-toggle-left"
  | "fa-toggle-off"
  | "fa-toggle-on"
  | "fa-toggle-right"
  | "fa-toggle-up"
  | "fa-trademark"
  | "fa-train"
  | "fa-transgender"
  | "fa-transgender-alt"
  | "fa-trash"
  | "fa-trash-o"
  | "fa-tree"
  | "fa-trello"
  | "fa-tripadvisor"
  | "fa-trophy"
  | "fa-truck"
  | "fa-try"
  | "fa-tty"
  | "fa-tumblr"
  | "fa-tumblr-square"
  | "fa-turkish-lira"
  | "fa-tv"
  | "fa-twitch"
  | "fa-twitter"
  | "fa-twitter-square"
  | "fa-umbrella"
  | "fa-underline"
  | "fa-undo"
  | "fa-universal-access"
  | "fa-university"
  | "fa-unlink"
  | "fa-unlock"
  | "fa-unlock-alt"
  | "fa-unsorted"
  | "fa-upload"
  | "fa-usb"
  | "fa-usd"
  | "fa-user"
  | "fa-user-circle"
  | "fa-user-circle-o"
  | "fa-user-md"
  | "fa-user-o"
  | "fa-user-plus"
  | "fa-user-secret"
  | "fa-user-times"
  | "fa-users"
  | "fa-vcard"
  | "fa-vcard-o"
  | "fa-venus"
  | "fa-venus-double"
  | "fa-venus-mars"
  | "fa-viacoin"
  | "fa-viadeo"
  | "fa-viadeo-square"
  | "fa-video-camera"
  | "fa-vimeo"
  | "fa-vimeo-square"
  | "fa-vine"
  | "fa-vk"
  | "fa-volume-control-phone"
  | "fa-volume-down"
  | "fa-volume-off"
  | "fa-volume-up"
  | "fa-warning"
  | "fa-wechat"
  | "fa-weibo"
  | "fa-weixin"
  | "fa-whatsapp"
  | "fa-wheelchair"
  | "fa-wheelchair-alt"
  | "fa-wifi"
  | "fa-wikipedia-w"
  | "fa-window-close"
  | "fa-window-close-o"
  | "fa-window-maximize"
  | "fa-window-minimize"
  | "fa-window-restore"
  | "fa-windows"
  | "fa-won"
  | "fa-wordpress"
  | "fa-wpbeginner"
  | "fa-wpexplorer"
  | "fa-wpforms"
  | "fa-wrench"
  | "fa-xing"
  | "fa-xing-square"
  | "fa-y-combinator"
  | "fa-y-combinator-square"
  | "fa-yahoo"
  | "fa-yc"
  | "fa-yc-square"
  | "fa-yelp"
  | "fa-yen"
  | "fa-yoast"
  | "fa-youtube"
  | "fa-youtube-play"
  | "fa-youtube-square";

export const FontawesomeIcons: { [name: string]: FontawesomeIcon } = {
  "500px": "fa-500px",
  "addressBook": "fa-address-book",
  "addressBookO": "fa-address-book-o",
  "addressCard": "fa-address-card",
  "addressCardO": "fa-address-card-o",
  "adjust": "fa-adjust",
  "adn": "fa-adn",
  "alignCenter": "fa-align-center",
  "alignJustify": "fa-align-justify",
  "alignLeft": "fa-align-left",
  "alignRight": "fa-align-right",
  "amazon": "fa-amazon",
  "ambulance": "fa-ambulance",
  "americanSignLanguageInterpreting": "fa-american-sign-language-interpreting",
  "anchor": "fa-anchor",
  "android": "fa-android",
  "angellist": "fa-angellist",
  "angleDoubleDown": "fa-angle-double-down",
  "angleDoubleLeft": "fa-angle-double-left",
  "angleDoubleRight": "fa-angle-double-right",
  "angleDoubleUp": "fa-angle-double-up",
  "angleDown": "fa-angle-down",
  "angleLeft": "fa-angle-left",
  "angleRight": "fa-angle-right",
  "angleUp": "fa-angle-up",
  "apple": "fa-apple",
  "archive": "fa-archive",
  "areaChart": "fa-area-chart",
  "arrowCircleDown": "fa-arrow-circle-down",
  "arrowCircleLeft": "fa-arrow-circle-left",
  "arrowCircleODown": "fa-arrow-circle-o-down",
  "arrowCircleOLeft": "fa-arrow-circle-o-left",
  "arrowCircleORight": "fa-arrow-circle-o-right",
  "arrowCircleOUp": "fa-arrow-circle-o-up",
  "arrowCircleRight": "fa-arrow-circle-right",
  "arrowCircleUp": "fa-arrow-circle-up",
  "arrowDown": "fa-arrow-down",
  "arrowLeft": "fa-arrow-left",
  "arrowRight": "fa-arrow-right",
  "arrowUp": "fa-arrow-up",
  "arrows": "fa-arrows",
  "arrowsAlt": "fa-arrows-alt",
  "arrowsH": "fa-arrows-h",
  "arrowsV": "fa-arrows-v",
  "aslInterpreting": "fa-asl-interpreting",
  "assistiveListeningSystems": "fa-assistive-listening-systems",
  "asterisk": "fa-asterisk",
  "at": "fa-at",
  "audioDescription": "fa-audio-description",
  "automobile": "fa-automobile",
  "backward": "fa-backward",
  "balanceScale": "fa-balance-scale",
  "ban": "fa-ban",
  "bandcamp": "fa-bandcamp",
  "bank": "fa-bank",
  "barChart": "fa-bar-chart",
  "barChartO": "fa-bar-chart-o",
  "barcode": "fa-barcode",
  "bars": "fa-bars",
  "bath": "fa-bath",
  "bathtub": "fa-bathtub",
  "battery": "fa-battery",
  "battery0": "fa-battery-0",
  "battery1": "fa-battery-1",
  "battery2": "fa-battery-2",
  "battery3": "fa-battery-3",
  "battery4": "fa-battery-4",
  "batteryEmpty": "fa-battery-empty",
  "batteryFull": "fa-battery-full",
  "batteryHalf": "fa-battery-half",
  "batteryQuarter": "fa-battery-quarter",
  "batteryThreeQuarters": "fa-battery-three-quarters",
  "bed": "fa-bed",
  "beer": "fa-beer",
  "behance": "fa-behance",
  "behanceSquare": "fa-behance-square",
  "bell": "fa-bell",
  "bellO": "fa-bell-o",
  "bellSlash": "fa-bell-slash",
  "bellSlashO": "fa-bell-slash-o",
  "bicycle": "fa-bicycle",
  "binoculars": "fa-binoculars",
  "birthdayCake": "fa-birthday-cake",
  "bitbucket": "fa-bitbucket",
  "bitbucketSquare": "fa-bitbucket-square",
  "bitcoin": "fa-bitcoin",
  "blackTie": "fa-black-tie",
  "blind": "fa-blind",
  "bluetooth": "fa-bluetooth",
  "bluetoothB": "fa-bluetooth-b",
  "bold": "fa-bold",
  "bolt": "fa-bolt",
  "bomb": "fa-bomb",
  "book": "fa-book",
  "bookmark": "fa-bookmark",
  "bookmarkO": "fa-bookmark-o",
  "braille": "fa-braille",
  "briefcase": "fa-briefcase",
  "btc": "fa-btc",
  "bug": "fa-bug",
  "building": "fa-building",
  "buildingO": "fa-building-o",
  "bullhorn": "fa-bullhorn",
  "bullseye": "fa-bullseye",
  "bus": "fa-bus",
  "buysellads": "fa-buysellads",
  "cab": "fa-cab",
  "calculator": "fa-calculator",
  "calendar": "fa-calendar",
  "calendarCheckO": "fa-calendar-check-o",
  "calendarMinusO": "fa-calendar-minus-o",
  "calendarO": "fa-calendar-o",
  "calendarPlusO": "fa-calendar-plus-o",
  "calendarTimesO": "fa-calendar-times-o",
  "camera": "fa-camera",
  "cameraRetro": "fa-camera-retro",
  "car": "fa-car",
  "caretDown": "fa-caret-down",
  "caretLeft": "fa-caret-left",
  "caretRight": "fa-caret-right",
  "caretSquareODown": "fa-caret-square-o-down",
  "caretSquareOLeft": "fa-caret-square-o-left",
  "caretSquareORight": "fa-caret-square-o-right",
  "caretSquareOUp": "fa-caret-square-o-up",
  "caretUp": "fa-caret-up",
  "cartArrowDown": "fa-cart-arrow-down",
  "cartPlus": "fa-cart-plus",
  "cc": "fa-cc",
  "ccAmex": "fa-cc-amex",
  "ccDinersClub": "fa-cc-diners-club",
  "ccDiscover": "fa-cc-discover",
  "ccJcb": "fa-cc-jcb",
  "ccMastercard": "fa-cc-mastercard",
  "ccPaypal": "fa-cc-paypal",
  "ccStripe": "fa-cc-stripe",
  "ccVisa": "fa-cc-visa",
  "certificate": "fa-certificate",
  "chain": "fa-chain",
  "chainBroken": "fa-chain-broken",
  "check": "fa-check",
  "checkCircle": "fa-check-circle",
  "checkCircleO": "fa-check-circle-o",
  "checkSquare": "fa-check-square",
  "checkSquareO": "fa-check-square-o",
  "chevronCircleDown": "fa-chevron-circle-down",
  "chevronCircleLeft": "fa-chevron-circle-left",
  "chevronCircleRight": "fa-chevron-circle-right",
  "chevronCircleUp": "fa-chevron-circle-up",
  "chevronDown": "fa-chevron-down",
  "chevronLeft": "fa-chevron-left",
  "chevronRight": "fa-chevron-right",
  "chevronUp": "fa-chevron-up",
  "child": "fa-child",
  "chrome": "fa-chrome",
  "circle": "fa-circle",
  "circleO": "fa-circle-o",
  "circleONotch": "fa-circle-o-notch",
  "circleThin": "fa-circle-thin",
  "clipboard": "fa-clipboard",
  "clockO": "fa-clock-o",
  "clone": "fa-clone",
  "close": "fa-close",
  "cloud": "fa-cloud",
  "cloudDownload": "fa-cloud-download",
  "cloudUpload": "fa-cloud-upload",
  "cny": "fa-cny",
  "code": "fa-code",
  "codeFork": "fa-code-fork",
  "codepen": "fa-codepen",
  "codiepie": "fa-codiepie",
  "coffee": "fa-coffee",
  "cog": "fa-cog",
  "cogs": "fa-cogs",
  "columns": "fa-columns",
  "comment": "fa-comment",
  "commentO": "fa-comment-o",
  "commenting": "fa-commenting",
  "commentingO": "fa-commenting-o",
  "comments": "fa-comments",
  "commentsO": "fa-comments-o",
  "compass": "fa-compass",
  "compress": "fa-compress",
  "connectdevelop": "fa-connectdevelop",
  "contao": "fa-contao",
  "copy": "fa-copy",
  "copyright": "fa-copyright",
  "creativeCommons": "fa-creative-commons",
  "creditCard": "fa-credit-card",
  "creditCardAlt": "fa-credit-card-alt",
  "crop": "fa-crop",
  "crosshairs": "fa-crosshairs",
  "css3": "fa-css3",
  "cube": "fa-cube",
  "cubes": "fa-cubes",
  "cut": "fa-cut",
  "cutlery": "fa-cutlery",
  "dashboard": "fa-dashboard",
  "dashcube": "fa-dashcube",
  "database": "fa-database",
  "deaf": "fa-deaf",
  "deafness": "fa-deafness",
  "dedent": "fa-dedent",
  "delicious": "fa-delicious",
  "desktop": "fa-desktop",
  "deviantart": "fa-deviantart",
  "diamond": "fa-diamond",
  "digg": "fa-digg",
  "dollar": "fa-dollar",
  "dotCircleO": "fa-dot-circle-o",
  "download": "fa-download",
  "dribbble": "fa-dribbble",
  "driversLicense": "fa-drivers-license",
  "driversLicenseO": "fa-drivers-license-o",
  "dropbox": "fa-dropbox",
  "drupal": "fa-drupal",
  "edge": "fa-edge",
  "edit": "fa-edit",
  "eercast": "fa-eercast",
  "eject": "fa-eject",
  "ellipsisH": "fa-ellipsis-h",
  "ellipsisV": "fa-ellipsis-v",
  "empire": "fa-empire",
  "envelope": "fa-envelope",
  "envelopeO": "fa-envelope-o",
  "envelopeOpen": "fa-envelope-open",
  "envelopeOpenO": "fa-envelope-open-o",
  "envelopeSquare": "fa-envelope-square",
  "envira": "fa-envira",
  "eraser": "fa-eraser",
  "etsy": "fa-etsy",
  "eur": "fa-eur",
  "euro": "fa-euro",
  "exchange": "fa-exchange",
  "exclamation": "fa-exclamation",
  "exclamationCircle": "fa-exclamation-circle",
  "exclamationTriangle": "fa-exclamation-triangle",
  "expand": "fa-expand",
  "expeditedssl": "fa-expeditedssl",
  "externalLink": "fa-external-link",
  "externalLinkSquare": "fa-external-link-square",
  "eye": "fa-eye",
  "eyeSlash": "fa-eye-slash",
  "eyedropper": "fa-eyedropper",
  "fa": "fa-fa",
  "facebook": "fa-facebook",
  "facebookF": "fa-facebook-f",
  "facebookOfficial": "fa-facebook-official",
  "facebookSquare": "fa-facebook-square",
  "fastBackward": "fa-fast-backward",
  "fastForward": "fa-fast-forward",
  "fax": "fa-fax",
  "feed": "fa-feed",
  "female": "fa-female",
  "fighterJet": "fa-fighter-jet",
  "file": "fa-file",
  "fileArchiveO": "fa-file-archive-o",
  "fileAudioO": "fa-file-audio-o",
  "fileCodeO": "fa-file-code-o",
  "fileExcelO": "fa-file-excel-o",
  "fileImageO": "fa-file-image-o",
  "fileMovieO": "fa-file-movie-o",
  "fileO": "fa-file-o",
  "filePdfO": "fa-file-pdf-o",
  "filePhotoO": "fa-file-photo-o",
  "filePictureO": "fa-file-picture-o",
  "filePowerpointO": "fa-file-powerpoint-o",
  "fileSoundO": "fa-file-sound-o",
  "fileText": "fa-file-text",
  "fileTextO": "fa-file-text-o",
  "fileVideoO": "fa-file-video-o",
  "fileWordO": "fa-file-word-o",
  "fileZipO": "fa-file-zip-o",
  "filesO": "fa-files-o",
  "film": "fa-film",
  "filter": "fa-filter",
  "fire": "fa-fire",
  "fireExtinguisher": "fa-fire-extinguisher",
  "firefox": "fa-firefox",
  "firstOrder": "fa-first-order",
  "flag": "fa-flag",
  "flagCheckered": "fa-flag-checkered",
  "flagO": "fa-flag-o",
  "flash": "fa-flash",
  "flask": "fa-flask",
  "flickr": "fa-flickr",
  "floppyO": "fa-floppy-o",
  "folder": "fa-folder",
  "folderO": "fa-folder-o",
  "folderOpen": "fa-folder-open",
  "folderOpenO": "fa-folder-open-o",
  "font": "fa-font",
  "fontAwesome": "fa-font-awesome",
  "fonticons": "fa-fonticons",
  "fortAwesome": "fa-fort-awesome",
  "forumbee": "fa-forumbee",
  "forward": "fa-forward",
  "foursquare": "fa-foursquare",
  "freeCodeCamp": "fa-free-code-camp",
  "frownO": "fa-frown-o",
  "futbolO": "fa-futbol-o",
  "gamepad": "fa-gamepad",
  "gavel": "fa-gavel",
  "gbp": "fa-gbp",
  "ge": "fa-ge",
  "gear": "fa-gear",
  "gears": "fa-gears",
  "genderless": "fa-genderless",
  "getPocket": "fa-get-pocket",
  "gg": "fa-gg",
  "ggCircle": "fa-gg-circle",
  "gift": "fa-gift",
  "git": "fa-git",
  "gitSquare": "fa-git-square",
  "github": "fa-github",
  "githubAlt": "fa-github-alt",
  "githubSquare": "fa-github-square",
  "gitlab": "fa-gitlab",
  "gittip": "fa-gittip",
  "glass": "fa-glass",
  "glide": "fa-glide",
  "glideG": "fa-glide-g",
  "globe": "fa-globe",
  "google": "fa-google",
  "googlePlus": "fa-google-plus",
  "googlePlusCircle": "fa-google-plus-circle",
  "googlePlusOfficial": "fa-google-plus-official",
  "googlePlusSquare": "fa-google-plus-square",
  "googleWallet": "fa-google-wallet",
  "graduationCap": "fa-graduation-cap",
  "gratipay": "fa-gratipay",
  "grav": "fa-grav",
  "group": "fa-group",
  "hSquare": "fa-h-square",
  "hackerNews": "fa-hacker-news",
  "handGrabO": "fa-hand-grab-o",
  "handLizardO": "fa-hand-lizard-o",
  "handODown": "fa-hand-o-down",
  "handOLeft": "fa-hand-o-left",
  "handORight": "fa-hand-o-right",
  "handOUp": "fa-hand-o-up",
  "handPaperO": "fa-hand-paper-o",
  "handPeaceO": "fa-hand-peace-o",
  "handPointerO": "fa-hand-pointer-o",
  "handRockO": "fa-hand-rock-o",
  "handScissorsO": "fa-hand-scissors-o",
  "handSpockO": "fa-hand-spock-o",
  "handStopO": "fa-hand-stop-o",
  "handshakeO": "fa-handshake-o",
  "hardOfHearing": "fa-hard-of-hearing",
  "hashtag": "fa-hashtag",
  "hddO": "fa-hdd-o",
  "header": "fa-header",
  "headphones": "fa-headphones",
  "heart": "fa-heart",
  "heartO": "fa-heart-o",
  "heartbeat": "fa-heartbeat",
  "history": "fa-history",
  "home": "fa-home",
  "hospitalO": "fa-hospital-o",
  "hotel": "fa-hotel",
  "hourglass": "fa-hourglass",
  "hourglass1": "fa-hourglass-1",
  "hourglass2": "fa-hourglass-2",
  "hourglass3": "fa-hourglass-3",
  "hourglassEnd": "fa-hourglass-end",
  "hourglassHalf": "fa-hourglass-half",
  "hourglassO": "fa-hourglass-o",
  "hourglassStart": "fa-hourglass-start",
  "houzz": "fa-houzz",
  "html5": "fa-html5",
  "iCursor": "fa-i-cursor",
  "idBadge": "fa-id-badge",
  "idCard": "fa-id-card",
  "idCardO": "fa-id-card-o",
  "ils": "fa-ils",
  "image": "fa-image",
  "imdb": "fa-imdb",
  "inbox": "fa-inbox",
  "indent": "fa-indent",
  "industry": "fa-industry",
  "info": "fa-info",
  "infoCircle": "fa-info-circle",
  "inr": "fa-inr",
  "instagram": "fa-instagram",
  "institution": "fa-institution",
  "internetExplorer": "fa-internet-explorer",
  "intersex": "fa-intersex",
  "ioxhost": "fa-ioxhost",
  "italic": "fa-italic",
  "joomla": "fa-joomla",
  "jpy": "fa-jpy",
  "jsfiddle": "fa-jsfiddle",
  "key": "fa-key",
  "keyboardO": "fa-keyboard-o",
  "krw": "fa-krw",
  "language": "fa-language",
  "laptop": "fa-laptop",
  "lastfm": "fa-lastfm",
  "lastfmSquare": "fa-lastfm-square",
  "leaf": "fa-leaf",
  "leanpub": "fa-leanpub",
  "legal": "fa-legal",
  "lemonO": "fa-lemon-o",
  "levelDown": "fa-level-down",
  "levelUp": "fa-level-up",
  "lifeBouy": "fa-life-bouy",
  "lifeBuoy": "fa-life-buoy",
  "lifeRing": "fa-life-ring",
  "lifeSaver": "fa-life-saver",
  "lightbulbO": "fa-lightbulb-o",
  "lineChart": "fa-line-chart",
  "link": "fa-link",
  "linkedin": "fa-linkedin",
  "linkedinSquare": "fa-linkedin-square",
  "linode": "fa-linode",
  "linux": "fa-linux",
  "list": "fa-list",
  "listAlt": "fa-list-alt",
  "listOl": "fa-list-ol",
  "listUl": "fa-list-ul",
  "locationArrow": "fa-location-arrow",
  "lock": "fa-lock",
  "longArrowDown": "fa-long-arrow-down",
  "longArrowLeft": "fa-long-arrow-left",
  "longArrowRight": "fa-long-arrow-right",
  "longArrowUp": "fa-long-arrow-up",
  "lowVision": "fa-low-vision",
  "magic": "fa-magic",
  "magnet": "fa-magnet",
  "mailForward": "fa-mail-forward",
  "mailReply": "fa-mail-reply",
  "mailReplyAll": "fa-mail-reply-all",
  "male": "fa-male",
  "map": "fa-map",
  "mapMarker": "fa-map-marker",
  "mapO": "fa-map-o",
  "mapPin": "fa-map-pin",
  "mapSigns": "fa-map-signs",
  "mars": "fa-mars",
  "marsDouble": "fa-mars-double",
  "marsStroke": "fa-mars-stroke",
  "marsStrokeH": "fa-mars-stroke-h",
  "marsStrokeV": "fa-mars-stroke-v",
  "maxcdn": "fa-maxcdn",
  "meanpath": "fa-meanpath",
  "medium": "fa-medium",
  "medkit": "fa-medkit",
  "meetup": "fa-meetup",
  "mehO": "fa-meh-o",
  "mercury": "fa-mercury",
  "microchip": "fa-microchip",
  "microphone": "fa-microphone",
  "microphoneSlash": "fa-microphone-slash",
  "minus": "fa-minus",
  "minusCircle": "fa-minus-circle",
  "minusSquare": "fa-minus-square",
  "minusSquareO": "fa-minus-square-o",
  "mixcloud": "fa-mixcloud",
  "mobile": "fa-mobile",
  "mobilePhone": "fa-mobile-phone",
  "modx": "fa-modx",
  "money": "fa-money",
  "moonO": "fa-moon-o",
  "mortarBoard": "fa-mortar-board",
  "motorcycle": "fa-motorcycle",
  "mousePointer": "fa-mouse-pointer",
  "music": "fa-music",
  "navicon": "fa-navicon",
  "neuter": "fa-neuter",
  "newspaperO": "fa-newspaper-o",
  "objectGroup": "fa-object-group",
  "objectUngroup": "fa-object-ungroup",
  "odnoklassniki": "fa-odnoklassniki",
  "odnoklassnikiSquare": "fa-odnoklassniki-square",
  "opencart": "fa-opencart",
  "openid": "fa-openid",
  "opera": "fa-opera",
  "optinMonster": "fa-optin-monster",
  "outdent": "fa-outdent",
  "pagelines": "fa-pagelines",
  "paintBrush": "fa-paint-brush",
  "paperPlane": "fa-paper-plane",
  "paperPlaneO": "fa-paper-plane-o",
  "paperclip": "fa-paperclip",
  "paragraph": "fa-paragraph",
  "paste": "fa-paste",
  "pause": "fa-pause",
  "pauseCircle": "fa-pause-circle",
  "pauseCircleO": "fa-pause-circle-o",
  "paw": "fa-paw",
  "paypal": "fa-paypal",
  "pencil": "fa-pencil",
  "pencilSquare": "fa-pencil-square",
  "pencilSquareO": "fa-pencil-square-o",
  "percent": "fa-percent",
  "phone": "fa-phone",
  "phoneSquare": "fa-phone-square",
  "photo": "fa-photo",
  "pictureO": "fa-picture-o",
  "pieChart": "fa-pie-chart",
  "piedPiper": "fa-pied-piper",
  "piedPiperAlt": "fa-pied-piper-alt",
  "piedPiperPp": "fa-pied-piper-pp",
  "pinterest": "fa-pinterest",
  "pinterestP": "fa-pinterest-p",
  "pinterestSquare": "fa-pinterest-square",
  "plane": "fa-plane",
  "play": "fa-play",
  "playCircle": "fa-play-circle",
  "playCircleO": "fa-play-circle-o",
  "plug": "fa-plug",
  "plus": "fa-plus",
  "plusCircle": "fa-plus-circle",
  "plusSquare": "fa-plus-square",
  "plusSquareO": "fa-plus-square-o",
  "podcast": "fa-podcast",
  "powerOff": "fa-power-off",
  "print": "fa-print",
  "productHunt": "fa-product-hunt",
  "puzzlePiece": "fa-puzzle-piece",
  "qq": "fa-qq",
  "qrcode": "fa-qrcode",
  "question": "fa-question",
  "questionCircle": "fa-question-circle",
  "questionCircleO": "fa-question-circle-o",
  "quora": "fa-quora",
  "quoteLeft": "fa-quote-left",
  "quoteRight": "fa-quote-right",
  "ra": "fa-ra",
  "random": "fa-random",
  "ravelry": "fa-ravelry",
  "rebel": "fa-rebel",
  "recycle": "fa-recycle",
  "reddit": "fa-reddit",
  "redditAlien": "fa-reddit-alien",
  "redditSquare": "fa-reddit-square",
  "refresh": "fa-refresh",
  "registered": "fa-registered",
  "remove": "fa-remove",
  "renren": "fa-renren",
  "reorder": "fa-reorder",
  "repeat": "fa-repeat",
  "reply": "fa-reply",
  "replyAll": "fa-reply-all",
  "resistance": "fa-resistance",
  "retweet": "fa-retweet",
  "rmb": "fa-rmb",
  "road": "fa-road",
  "rocket": "fa-rocket",
  "rotateLeft": "fa-rotate-left",
  "rotateRight": "fa-rotate-right",
  "rouble": "fa-rouble",
  "rss": "fa-rss",
  "rssSquare": "fa-rss-square",
  "rub": "fa-rub",
  "ruble": "fa-ruble",
  "rupee": "fa-rupee",
  "s15": "fa-s15",
  "safari": "fa-safari",
  "save": "fa-save",
  "scissors": "fa-scissors",
  "scribd": "fa-scribd",
  "search": "fa-search",
  "searchMinus": "fa-search-minus",
  "searchPlus": "fa-search-plus",
  "sellsy": "fa-sellsy",
  "send": "fa-send",
  "sendO": "fa-send-o",
  "server": "fa-server",
  "share": "fa-share",
  "shareAlt": "fa-share-alt",
  "shareAltSquare": "fa-share-alt-square",
  "shareSquare": "fa-share-square",
  "shareSquareO": "fa-share-square-o",
  "shekel": "fa-shekel",
  "sheqel": "fa-sheqel",
  "shield": "fa-shield",
  "ship": "fa-ship",
  "shirtsinbulk": "fa-shirtsinbulk",
  "shoppingBag": "fa-shopping-bag",
  "shoppingBasket": "fa-shopping-basket",
  "shoppingCart": "fa-shopping-cart",
  "shower": "fa-shower",
  "signIn": "fa-sign-in",
  "signLanguage": "fa-sign-language",
  "signOut": "fa-sign-out",
  "signal": "fa-signal",
  "signing": "fa-signing",
  "simplybuilt": "fa-simplybuilt",
  "sitemap": "fa-sitemap",
  "skyatlas": "fa-skyatlas",
  "skype": "fa-skype",
  "slack": "fa-slack",
  "sliders": "fa-sliders",
  "slideshare": "fa-slideshare",
  "smileO": "fa-smile-o",
  "snapchat": "fa-snapchat",
  "snapchatGhost": "fa-snapchat-ghost",
  "snapchatSquare": "fa-snapchat-square",
  "snowflakeO": "fa-snowflake-o",
  "soccerBallO": "fa-soccer-ball-o",
  "sort": "fa-sort",
  "sortAlphaAsc": "fa-sort-alpha-asc",
  "sortAlphaDesc": "fa-sort-alpha-desc",
  "sortAmountAsc": "fa-sort-amount-asc",
  "sortAmountDesc": "fa-sort-amount-desc",
  "sortAsc": "fa-sort-asc",
  "sortDesc": "fa-sort-desc",
  "sortDown": "fa-sort-down",
  "sortNumericAsc": "fa-sort-numeric-asc",
  "sortNumericDesc": "fa-sort-numeric-desc",
  "sortUp": "fa-sort-up",
  "soundcloud": "fa-soundcloud",
  "spaceShuttle": "fa-space-shuttle",
  "spinner": "fa-spinner",
  "spoon": "fa-spoon",
  "spotify": "fa-spotify",
  "square": "fa-square",
  "squareO": "fa-square-o",
  "stackExchange": "fa-stack-exchange",
  "stackOverflow": "fa-stack-overflow",
  "star": "fa-star",
  "starHalf": "fa-star-half",
  "starHalfEmpty": "fa-star-half-empty",
  "starHalfFull": "fa-star-half-full",
  "starHalfO": "fa-star-half-o",
  "starO": "fa-star-o",
  "steam": "fa-steam",
  "steamSquare": "fa-steam-square",
  "stepBackward": "fa-step-backward",
  "stepForward": "fa-step-forward",
  "stethoscope": "fa-stethoscope",
  "stickyNote": "fa-sticky-note",
  "stickyNoteO": "fa-sticky-note-o",
  "stop": "fa-stop",
  "stopCircle": "fa-stop-circle",
  "stopCircleO": "fa-stop-circle-o",
  "streetView": "fa-street-view",
  "strikethrough": "fa-strikethrough",
  "stumbleupon": "fa-stumbleupon",
  "stumbleuponCircle": "fa-stumbleupon-circle",
  "subscript": "fa-subscript",
  "subway": "fa-subway",
  "suitcase": "fa-suitcase",
  "sunO": "fa-sun-o",
  "superpowers": "fa-superpowers",
  "superscript": "fa-superscript",
  "support": "fa-support",
  "table": "fa-table",
  "tablet": "fa-tablet",
  "tachometer": "fa-tachometer",
  "tag": "fa-tag",
  "tags": "fa-tags",
  "tasks": "fa-tasks",
  "taxi": "fa-taxi",
  "telegram": "fa-telegram",
  "television": "fa-television",
  "tencentWeibo": "fa-tencent-weibo",
  "terminal": "fa-terminal",
  "textHeight": "fa-text-height",
  "textWidth": "fa-text-width",
  "th": "fa-th",
  "thLarge": "fa-th-large",
  "thList": "fa-th-list",
  "themeisle": "fa-themeisle",
  "thermometer": "fa-thermometer",
  "thermometer0": "fa-thermometer-0",
  "thermometer1": "fa-thermometer-1",
  "thermometer2": "fa-thermometer-2",
  "thermometer3": "fa-thermometer-3",
  "thermometer4": "fa-thermometer-4",
  "thermometerEmpty": "fa-thermometer-empty",
  "thermometerFull": "fa-thermometer-full",
  "thermometerHalf": "fa-thermometer-half",
  "thermometerQuarter": "fa-thermometer-quarter",
  "thermometerThreeQuarters": "fa-thermometer-three-quarters",
  "thumbTack": "fa-thumb-tack",
  "thumbsDown": "fa-thumbs-down",
  "thumbsODown": "fa-thumbs-o-down",
  "thumbsOUp": "fa-thumbs-o-up",
  "thumbsUp": "fa-thumbs-up",
  "ticket": "fa-ticket",
  "times": "fa-times",
  "timesCircle": "fa-times-circle",
  "timesCircleO": "fa-times-circle-o",
  "timesRectangle": "fa-times-rectangle",
  "timesRectangleO": "fa-times-rectangle-o",
  "tint": "fa-tint",
  "toggleDown": "fa-toggle-down",
  "toggleLeft": "fa-toggle-left",
  "toggleOff": "fa-toggle-off",
  "toggleOn": "fa-toggle-on",
  "toggleRight": "fa-toggle-right",
  "toggleUp": "fa-toggle-up",
  "trademark": "fa-trademark",
  "train": "fa-train",
  "transgender": "fa-transgender",
  "transgenderAlt": "fa-transgender-alt",
  "trash": "fa-trash",
  "trashO": "fa-trash-o",
  "tree": "fa-tree",
  "trello": "fa-trello",
  "tripadvisor": "fa-tripadvisor",
  "trophy": "fa-trophy",
  "truck": "fa-truck",
  "try": "fa-try",
  "tty": "fa-tty",
  "tumblr": "fa-tumblr",
  "tumblrSquare": "fa-tumblr-square",
  "turkishLira": "fa-turkish-lira",
  "tv": "fa-tv",
  "twitch": "fa-twitch",
  "twitter": "fa-twitter",
  "twitterSquare": "fa-twitter-square",
  "umbrella": "fa-umbrella",
  "underline": "fa-underline",
  "undo": "fa-undo",
  "universalAccess": "fa-universal-access",
  "university": "fa-university",
  "unlink": "fa-unlink",
  "unlock": "fa-unlock",
  "unlockAlt": "fa-unlock-alt",
  "unsorted": "fa-unsorted",
  "upload": "fa-upload",
  "usb": "fa-usb",
  "usd": "fa-usd",
  "user": "fa-user",
  "userCircle": "fa-user-circle",
  "userCircleO": "fa-user-circle-o",
  "userMd": "fa-user-md",
  "userO": "fa-user-o",
  "userPlus": "fa-user-plus",
  "userSecret": "fa-user-secret",
  "userTimes": "fa-user-times",
  "users": "fa-users",
  "vcard": "fa-vcard",
  "vcardO": "fa-vcard-o",
  "venus": "fa-venus",
  "venusDouble": "fa-venus-double",
  "venusMars": "fa-venus-mars",
  "viacoin": "fa-viacoin",
  "viadeo": "fa-viadeo",
  "viadeoSquare": "fa-viadeo-square",
  "videoCamera": "fa-video-camera",
  "vimeo": "fa-vimeo",
  "vimeoSquare": "fa-vimeo-square",
  "vine": "fa-vine",
  "vk": "fa-vk",
  "volumeControlPhone": "fa-volume-control-phone",
  "volumeDown": "fa-volume-down",
  "volumeOff": "fa-volume-off",
  "volumeUp": "fa-volume-up",
  "warning": "fa-warning",
  "wechat": "fa-wechat",
  "weibo": "fa-weibo",
  "weixin": "fa-weixin",
  "whatsapp": "fa-whatsapp",
  "wheelchair": "fa-wheelchair",
  "wheelchairAlt": "fa-wheelchair-alt",
  "wifi": "fa-wifi",
  "wikipediaW": "fa-wikipedia-w",
  "windowClose": "fa-window-close",
  "windowCloseO": "fa-window-close-o",
  "windowMaximize": "fa-window-maximize",
  "windowMinimize": "fa-window-minimize",
  "windowRestore": "fa-window-restore",
  "windows": "fa-windows",
  "won": "fa-won",
  "wordpress": "fa-wordpress",
  "wpbeginner": "fa-wpbeginner",
  "wpexplorer": "fa-wpexplorer",
  "wpforms": "fa-wpforms",
  "wrench": "fa-wrench",
  "xing": "fa-xing",
  "xingSquare": "fa-xing-square",
  "yCombinator": "fa-y-combinator",
  "yCombinatorSquare": "fa-y-combinator-square",
  "yahoo": "fa-yahoo",
  "yc": "fa-yc",
  "ycSquare": "fa-yc-square",
  "yelp": "fa-yelp",
  "yen": "fa-yen",
  "yoast": "fa-yoast",
  "youtube": "fa-youtube",
  "youtubePlay": "fa-youtube-play",
  "youtubeSquare": "fa-youtube-square"
}
